name: mmtf-pyspark 

channels:
  - conda-forge
  - anaconda
  - bioconda 

dependencies:
  - python=3.8
  - openjdk=8.0.152
  - pyspark=3.3.1
  - biopython=1.80
  - numba=0.56.*
  - numpy=1.23.*
  - jupyterlab=3.6.*
  - py3dmol=2.*
  - ipywidgets=8.0.*
  - pip
  - pip:
      - git+https://github.com/sbl-sdsc/mmtf-pyspark.git 

variables:
  SPARK_DRIVER_MEMORY: 16G
  SPARK_DRIVER_MAXRESULTSIZE: 4G
  SPARK_WORKER_MEMORY: 4G
